version: '3.9'

services:

  mongodb:
    image: mongo:7.0
    container_name: blackjack-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: blackjack
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: blackjack-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack
      MYSQL_USER: blackjack
      MYSQL_PASSWORD: blackjack
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mongo_data:
  mysql_data: